/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedRetrievalsRouteImport } from './routes/_authenticated/retrievals'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDisposalRouteImport } from './routes/_authenticated/disposal'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCartsRouteImport } from './routes/_authenticated/carts'
import { Route as AuthenticatedCartsNewRouteImport } from './routes/_authenticated/carts.new'
import { Route as AuthenticatedCartsCartIdRouteImport } from './routes/_authenticated/carts.$cartId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRetrievalsRoute = AuthenticatedRetrievalsRouteImport.update({
  id: '/retrievals',
  path: '/retrievals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDisposalRoute = AuthenticatedDisposalRouteImport.update({
  id: '/disposal',
  path: '/disposal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCartsRoute = AuthenticatedCartsRouteImport.update({
  id: '/carts',
  path: '/carts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCartsNewRoute = AuthenticatedCartsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedCartsRoute,
} as any)
const AuthenticatedCartsCartIdRoute =
  AuthenticatedCartsCartIdRouteImport.update({
    id: '/$cartId',
    path: '/$cartId',
    getParentRoute: () => AuthenticatedCartsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carts': typeof AuthenticatedCartsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/disposal': typeof AuthenticatedDisposalRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/retrievals': typeof AuthenticatedRetrievalsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/carts/$cartId': typeof AuthenticatedCartsCartIdRoute
  '/carts/new': typeof AuthenticatedCartsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carts': typeof AuthenticatedCartsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/disposal': typeof AuthenticatedDisposalRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/retrievals': typeof AuthenticatedRetrievalsRoute
  '/search': typeof AuthenticatedSearchRoute
  '/carts/$cartId': typeof AuthenticatedCartsCartIdRoute
  '/carts/new': typeof AuthenticatedCartsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/carts': typeof AuthenticatedCartsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/disposal': typeof AuthenticatedDisposalRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/retrievals': typeof AuthenticatedRetrievalsRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/carts/$cartId': typeof AuthenticatedCartsCartIdRoute
  '/_authenticated/carts/new': typeof AuthenticatedCartsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/carts'
    | '/dashboard'
    | '/disposal'
    | '/documents'
    | '/retrievals'
    | '/search'
    | '/carts/$cartId'
    | '/carts/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/carts'
    | '/dashboard'
    | '/disposal'
    | '/documents'
    | '/retrievals'
    | '/search'
    | '/carts/$cartId'
    | '/carts/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/carts'
    | '/_authenticated/dashboard'
    | '/_authenticated/disposal'
    | '/_authenticated/documents'
    | '/_authenticated/retrievals'
    | '/_authenticated/search'
    | '/_authenticated/carts/$cartId'
    | '/_authenticated/carts/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/retrievals': {
      id: '/_authenticated/retrievals'
      path: '/retrievals'
      fullPath: '/retrievals'
      preLoaderRoute: typeof AuthenticatedRetrievalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/disposal': {
      id: '/_authenticated/disposal'
      path: '/disposal'
      fullPath: '/disposal'
      preLoaderRoute: typeof AuthenticatedDisposalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carts': {
      id: '/_authenticated/carts'
      path: '/carts'
      fullPath: '/carts'
      preLoaderRoute: typeof AuthenticatedCartsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carts/new': {
      id: '/_authenticated/carts/new'
      path: '/new'
      fullPath: '/carts/new'
      preLoaderRoute: typeof AuthenticatedCartsNewRouteImport
      parentRoute: typeof AuthenticatedCartsRoute
    }
    '/_authenticated/carts/$cartId': {
      id: '/_authenticated/carts/$cartId'
      path: '/$cartId'
      fullPath: '/carts/$cartId'
      preLoaderRoute: typeof AuthenticatedCartsCartIdRouteImport
      parentRoute: typeof AuthenticatedCartsRoute
    }
  }
}

interface AuthenticatedCartsRouteChildren {
  AuthenticatedCartsCartIdRoute: typeof AuthenticatedCartsCartIdRoute
  AuthenticatedCartsNewRoute: typeof AuthenticatedCartsNewRoute
}

const AuthenticatedCartsRouteChildren: AuthenticatedCartsRouteChildren = {
  AuthenticatedCartsCartIdRoute: AuthenticatedCartsCartIdRoute,
  AuthenticatedCartsNewRoute: AuthenticatedCartsNewRoute,
}

const AuthenticatedCartsRouteWithChildren =
  AuthenticatedCartsRoute._addFileChildren(AuthenticatedCartsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCartsRoute: typeof AuthenticatedCartsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDisposalRoute: typeof AuthenticatedDisposalRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedRetrievalsRoute: typeof AuthenticatedRetrievalsRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCartsRoute: AuthenticatedCartsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDisposalRoute: AuthenticatedDisposalRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedRetrievalsRoute: AuthenticatedRetrievalsRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
